### ISSUE TITLE
More resources

### ISSUE THREAD

**Issue by dd23** [OpenMined/awesome-ai-privacy#4]
Hi,
This is not really an _issue_, but more of a pointer to possibly further relevant work that you might want to include to your list.

Here's an entire list of things for "open-source software designed for MPC as well as introductory material ":
https://github.com/rdragos/awesome-mpc

Since I'm working on it and it seems like a good fit in general: The ABY framework for mixed-protocol MPC. Can certainly be used to implement ML solutions, even if that is not explicitly mentioned in the original paper:
https://github.com/encryptogroup/aby

And a work from my colleague, which specifically looked at ML examples and is basically an extension to ABY:
https://eprint.iacr.org/2017/1164

Let me know if you have questions, or if I should just send a pull request...

**Comment by robert-wagner** [comment]
Hi,
Thank you so much for these resources. I'll work on getting them incorporated asap.

I'm not sure how aby wasn't already on there as it's come up several times through the work on openmined.

Would love to talk you about aby at some point.

Thank you again!
